feat: add footer section and responsiveness from mobile to desktop
TheGymRwanda/zzz-unit8-red pull request #15
Opened 2022-11-24 09:36 UTC by hirwaaldo1

## Describe your changes
Created a Footer component in the layout folder, added content in footer file and  it's responsive  to mobile , iPad , tablet and desktop
## Issue ticket number and link
id->#015
link->[here](https://www.notion.so/apeunit/Footer-section-81beec652681437fbd2fbce1ef769591)
## Tasks completed
- [x] added footer file
- [x] remove unnecessary file  
- [x] footer content it's responsiveness to all devices   
## Tasks not completed
- [x] we haven't removed underline on footer links 
## Screenshots (if needed)

2022-11-24 10:26 UTC, izzett222 requested changes
the footer margin-top is not present, could you add it.

2022-11-24 10:27 UTC, mhenriette requested changes

2022-11-24 10:27 UTC, mhenriette commented on pages/index.jsx
> +      <Wrapper>
Wrap the footer in the footer file not in the pages' file

2022-11-24 17:21 UTC, mhenriette approved these changes

2022-11-25 07:32 UTC, izzett222 approved these changes

2022-11-25 07:33 UTC, merged