Ft/blog carousel
TheGymRwanda/zzz-unit8-red pull request #36
Opened 2022-12-06 14:48 UTC by hirwaaldo1

## Describe your changes
Added slide functionality, responsive, and button functionality
## Issue ticket number and link
id->#026
link->[here](https://www.notion.so/apeunit/blog-carousel-2394f918cdd54220b0f1a1a083dba182)
## Tasks completed
- [x] Blog Responsive
- [x]  Carousel functionality
- [x]  Button Functionality
## Tasks not completed
none
## Screenshots (if needed)

2022-12-07 17:15 UTC, Ntwali-Josue requested changes
Hey @hirwaaldo1, Please fix this issue and the one under the review comments, you'll be good to go

- Your blog cards do not have the required shadows, please improve them to be exactly as the ones in Figma. Checkout the differences between your blog cards versions with the original designs from figma. 

**Your cards**

![image](https://user-images.githubusercontent.com/58233753/206245815-f2c05271-e4f3-4d85-9af4-6abec122019a.png)

 **Original Design**

![image](https://user-images.githubusercontent.com/58233753/206246067-fbfb23bb-140f-4217-b873-dabf9e6df205.png)

2022-12-07 17:15 UTC, Ntwali-Josue commented on components/sections/homepage/Blog.jsx
> +                  />
Use descriptive mapping parameters

2022-12-07 17:30 UTC, izzett222 requested changes

2022-12-07 17:30 UTC, izzett222 commented on components/sections/homepage/Blog.jsx
> +  const nexto = () => {
could you find a more descriptive name for the function

2022-12-07 17:30 UTC, izzett222 commented on components/sections/homepage/Blog.jsx
> +  const prevo = () => {
could you find a more descriptive name for the function

2022-12-07 17:30 UTC, izzett222 commented on components/sections/homepage/Blog.jsx
> +              onSlideChange={(e) => {
Can you remove the inline event handler function and declare it at the top so that it is easier to read the jsx

2022-12-07 17:30 UTC, izzett222 commented on components/ui/BlogCard.jsx
> +    <div className=" max-w-112 xl:min-w-lg  h-full box-border p-5 flex flex-col rounded-sm border-0.25 border-solid border-grey-400 shadow-md gap-9.5 justify-between ">
Could you remove the extra space in the class name  string

2022-12-15 18:11 UTC, Ntwali-Josue approved these changes

2022-12-20 10:28 UTC, izzett222 approved these changes

2022-12-22 08:47 UTC, mutesialine approved these changes
Well done. it's looks good

2022-12-22 08:47 UTC, merged