fix: change the width  of expertise section on desktop version
TheGymRwanda/zzz-unit8-red pull request #37
Opened 2022-12-06 15:28 UTC by mutesialine

## Describe your changes
changed the width of expertise section  on desktop and configured it in tailwindconfig 
## Issue ticket number and link
id->40
link->[here](https://www.notion.so/apeunit/Expertise-Section-Desktop-Tablet-Mobile-Issue-with-the-section-width-f6c536dcd5654ddfa675e43869dc8fb0)

## Tasks completed

- [x] changed the width from 656px to 646px( on xl breakpoint)
- [x]added width in tailwindconfig
## Tasks not completed
None
## Screenshots (if needed)

2022-12-07 17:05 UTC, hirwaaldo1 approved these changes
Looks good

2022-12-07 17:19 UTC, Ntwali-Josue approved these changes
Well done 🥇

2022-12-12 14:29 UTC, izzett222 requested changes

2022-12-12 14:29 UTC, izzett222 commented on tailwind.config.js
> +        40.37:"40.375rem",  //646px
Could you divide the px value by four rather than 16 for the custom property key? The method of dividing by four would be consistent with tailwindcss

2022-12-15 13:13 UTC, izzett222 approved these changes

2022-12-15 13:14 UTC, merged