Bg/expertise paragraph
TheGymRwanda/zzz-unit8-red pull request #38
Opened 2022-12-06 18:34 UTC by mutesialine

## Describe your changes
created  expertise data   file  from data folder and removed duplicate  of data in expertise section

## Issue ticket number and link
id->43
link->[here](https://www.notion.so/apeunit/Fix-Bugs-in-the-Expertise-section-01150e75161d4b4c96d33093f6cc8c42)
## Tasks completed
- [x] created expertiseList file in data folder
- [x]  added content in expertiseList file
- [x] removed duplicate of data in expertise section
## Tasks not completed
None
## Screenshots (if needed)

2022-12-07 17:28 UTC, Ntwali-Josue requested changes
Hey @mutesialine, Work on the review under the comments section. This will also fix your deployment issue you are having.

2022-12-07 17:28 UTC, Ntwali-Josue commented on components/sections/homepage/Expertise.jsx
> +            ))}
Give your paragraph a unique key value.

2022-12-07 18:02 UTC, Ntwali-Josue approved these changes
Well done @mutesialine and @rithaven 👍🏾

2022-12-12 14:55 UTC, izzett222 requested changes

2022-12-12 14:55 UTC, izzett222 commented on components/sections/homepage/Expertise.jsx
> +export default function Expertise({}) {
Could you remove the empty object destructuring?

2022-12-12 19:10 UTC, mhenriette approved these changes

2022-12-15 11:27 UTC, hirwaaldo1 approved these changes
Well Done

2022-12-15 13:26 UTC, izzett222 approved these changes

2022-12-15 13:26 UTC, merged