Refactor: refactoring footer anchor tags
TheGymRwanda/zzz-unit8-red pull request #43
Opened 2022-12-12 16:42 UTC by Ntwali-Josue

## Describe your changes

## Issue ticket number and link

## Tasks completed

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] etc

## Tasks not completed

- [ ] i haven't performed a review on my code
- [ ] i haven't added requested features yet
- [ ] etc

## Screenshots (if needed)

2022-12-12 18:53 UTC, mutesialine approved these changes

2022-12-12 19:18 UTC, mhenriette approved these changes
LGTM!!

2022-12-13 20:51 UTC, hirwaaldo1 requested changes
@Ntwali-Josue hello, as there mention in the last review the second paragraph does not have more tag links you can remove them on the `about` and `What We do` tabs

2022-12-13 20:54 UTC, hirwaaldo1 approved these changes

2022-12-13 20:54 UTC, merged